# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev31+g02761c8.d20230211'
__version_tuple__ = version_tuple = (0, 1, 'dev31', 'g02761c8.d20230211')
